### ISSUE TITLE
Acho que tenho algo digno de mostrar...

### ISSUE THREAD

**Issue by lucianolimafer** [rock-apps/vaga-react#2]
Meu repo: https://github.com/lucianolimafer/vaga-react/tree/main/mobile

Meu protótipo de guia: https://www.figma.com/file/F1vhMS5wkXQNykCXCSRo7E/ecommerce

Espero feedback, se possível.

**Comment by erickne** [comment]
Olá Luciano!

Obrigado pelo retorno. Iremos avaliar e entraremos em contato.

Abraços.
